version: "3"

services:
  mysql:
    image: mysql
    volumes:
        - ./database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "db"
  
  backend:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - mysql
    
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - backend

volumes:
  .:
  database:
  static:
